sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc-5
    - os: linux
      compiler: clang-3.6
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-5

install:
  - if [ "$CXX" = "g++" -a "$TRAVIS_OS_NAME" = "linux" ]; then
      export CXX="g++-5";
    fi
  - if [ "$CXX" = "clang++" -a "$TRAVIS_OS_NAME" = "linux" ]; then
      export CXX="clang++-3.6";
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install libevent;
    fi

script:
  - make CXX=$CXX
