#!/bin/sh -e
# Demonstrates how one could run a measurement-kit test as a script

if [ $# -lt 1 ]; then
    echo "usage: $0 script [script-options]" 1>&2
    exit 1
fi

if [ $(uname) = "Darwin" ]; then
    LIBEVENT=/usr/local/lib/libevent.dylib
elif [ $(uname) = "Linux" ]; then
    LIBEVENT=/usr/lib/libevent.so
else
    echo "FATAL: unknown uname: $(uname)" 1>&2
    exit 1
fi

SCRIPT=$1
shift
cat $SCRIPT | clang++ -c -emit-llvm -Wall -Wextra -std=c++14 -o- -xc++ - | \
    lli -load=$LIBEVENT - -- "$@"
